OPENAI_API_KEY: "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"
SERPER_API_KEY: "YOUR API KEY"
LANGSMITH_API_KEY: "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"
LANGCHAIN_TRACING_V2: "true"
LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
LANGCHAIN_PROJECT: "Marketing_Agent"